pre_filefilter: ['- tools/example/*', '+ *']

linters:
  - header:
  - import:
      packages: ['cardboardlint']
  - namespace:
      filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py', '+ *.py', '+ *.pyx']
  - pylint:
  - pycodestyle:
  - pydocstyle:
  - whitespace:
      filefilter: ['- *.patch', '- *.diff', '+ *.*']
  - yamllint:
