pre_filefilter: ['+ tools/example/.cardboardlint.yml', '- tools/example/*', '+ *']

linters:
  - header:
      extra: []
      shebang: '#!/usr/bin/env python3'
  - import:
      packages: ['cardboardlint']
  - namespace:
      filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py',
                   '- cardboardlint/linter_*.py', '+ *.py', '+ *.pyx']
  - pylint:
  - pycodestyle:
      config: .pycodestylerc
  - autopep8:
      config: .pycodestylerc
      line-range: 79 100
  - pydocstyle:
  - whitespace:
      filefilter: ['- *.patch', '- *.diff', '+ *.*']
  - yamllint:
      filefilter: ['- *conda.recipe/meta.yaml', '+ *.yml', '+ *.yaml']
