matrix:
  include:
    - os: linux
      dist: xenial
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.6"
        - ROBERTO_DEPLOY_BINARY=1
    - os: linux
      dist: xenial
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.7"
        - ROBERTO_DEPLOY_NOARCH=1
        - ROBERTO_DEPLOY_BINARY=1
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.6"
        - ROBERTO_DEPLOY_BINARY=1
    - os: osx
      osx_image: xcode9.4
      language: generic
      env:
        - ROBERTO_CONDA_PINNING="python 3.7"
        - ROBERTO_DEPLOY_BINARY=1

env:
  global:
    # Install conda in a *sub*directory of a directory cached by travis.
    - ROBERTO_CONDA_BASE_PATH=${HOME}/cache/miniconda3
    # Tell Roberto to upload coverage results
    - ROBERTO_UPLOAD_COVERAGE=1
    # Build conda packages outside the miniconda tree, to avoid caching.
    # This makes it possible to still deploy packages after cache cleaning.
    - CONDA_BLD_PATH=${HOME}/conda-bld
    # Tell roberto which branch is being merged into, in case of a PR.
    - ROBERTO_GIT_MERGE_BRANCH=${TRAVIS_BRANCH}
    # Debugging options
    # - HUB_VERBOSE=1

    # GITHUB_TOKEN
    # yamllint disable-line rule:line-length
    - secure: "ng/PpTXzeDn+1s9N9cwq5JBRIlbCzHKhL2vVbxbGgg03veHRovbzN5DcwAdWT5bGXdiXT1dcEY/nBsvDqLmdN6qjf/fcKBt8LXqG+rdnyvulULClLbCuh5aGnVxPagUMoIxYh99loAMwxreJcho8MnPNCOP5f0DKRh1b8DbmhZX5zM92xWKnOO0oSAOdu6gymUsfppZnyIEh11hJT0go9LJLfJu3gtnVIzsfRrayj4hYwLm6PpLBDMeuiur4RO0TCm6aiwDAy+Kf8gvuSb0eU4ZfyqGDStpGiC+aaR0Vm20XoM8YGNblnWIEYFJTTJYaCZw37GFE9XMgmBxECJVv3/XzutaDm9ioUejPDfwgoDd9uGXPgMs8nEk00TUvcZbTGP5gOcZvJs61CZ7KCfDn5RmGtDNvjUXes91qAJtwqqeksYFPXUmoodZhaOuFZ4vdQ+NHY5DDzBOS7RcBfWgmxA8SRWmneR2Q2Aqw4KqGTaliYU5CQp6zfLTNYsod0PGiTxRGl2uty3qyDnT5PH3e0P7yT8fQhcuF80yys29eFKVmiUBGDycJ/5kRMRWYJwNLH3FJKnBM2aHXGRJVPwwlms+XPiOEaVGCzCJCvn2ISIZ9zMDbH4dpXRbTMIeBtsAkmdR2W9mHQxz4nqG7avZMz8qMak1MDCfnLf3kMVLhlDk="
    # ANACONDA_API_TOKEN
    # yamllint disable-line rule:line-length
    - secure: "M+qeOfcpAknb4DtHuisAQfXN9BsivmivM930who/gSp9oaXPPLhzEpNDT2NWrf7dMsS3jDmYxPn0aH5jEn17WHA22dfeICTEvYkIi3YMIuVYY0uluaDSu16dLwPJcJTdsfniMsnFpasxVZTXDM+qF/9ANSNKP6Mno5qapSQPZnTrhWCcmGwIo5ZH/s6Mq+eTgQI4uQJxNJqV3keEk6YTR/Cml0b5VkWSgl2R+qdBp4YJezuoiYbvrm+pVPzi4vsTV/HptXHvHY67McZB/Y5PEXQqQ+1UpZfIVMzcByBIQWI3SAAOT3+uOdgqEJ5Rw4kWcX+TeDpqCZ3VGQcW2li0QkKrefadS1ncQMqwzQBomzGy+qt43tag4jwyQIJ2Bcw/EWlYAid/nZZba98CA42U4tqtZ2ENKWWVkzoEBpaR247nLzWni+rLszf+nDUOaYcAkVqJlWMfrIbUsAB/exa5poKLS3xwFENjLOA2b458jEYRGTFMgdLkfgFW10SqzvFgoEke1dYeu1OsfZ7snXJks3lwG+OC8Pl89toIQnkF8dMrDFq1O/Ic9LWvYciJdAFB2zHpO6+5cH+NlWpBOpEZzek/aIbg11VZK2j+5SgTqNAO40pqtrKn5ANODuIqQN6dgZrl0qv+aV5yyOGGyrJYWOGpcBW0v4vrlqpYBBmsU/U="
    # TWINE_PASSWORD
    # yamllint disable-line rule:line-length
    - secure: "tVPyMCJBH7nWaRG/IijCv/vmuZbOO8pbzkouVPg9e58bWPa40aFnPbhxmNxc14Oz7FD5dmPRo0r00aEgt+B52fQiHGKZCVbaPkvgqV41XwSMivlJ798F7GJUi7uAvJSwm4737kwAGGaQpPcKb3ydr/3OR59H99BXo0snsfbFXrYhRZNNOmuwC5TMYjrjRVDnP9jg2kJ13oOSDXiOMM3W8/pa6hnTf1wSW1wG3p40PXIbpZBTg4XFzV2gBKSy4hC7vGD9LnVqfeUQVXQMlPQGFuO7et+4SOokdCzXPMmNC3NwgtZaU0JKse4eqKSChHgv80sxzutVQiDcnbElSOuscwM3/Zv7Qq4GOqyrnA0i8Gq6Dx1grvYfxX/92XpzjpfARfoSC2zNKAxlsFjHzULCscaC6/QoSnttO7GWlGgZLKnui9hC+N1YhivRFYELYoNY9EtxkuvBj2mvOEkGM/fBmcW1ed1I5gKhwKJPLL5RZ8eN6ekXZqWA86G+Y6D1d2hn0HqUgm1RzlUOsW96Z/SCuGM+sZpOEaaChLNOIjAfq06MaEJPA5OxWLFw1/sGddKRaWa82CGN19obhAEYj5mEUkXv15MJsrasQrIqqc9e/vcz9xtmF21Lc4nsanbLLpEoZKKcQ4y0wWw4bmNKyHt++CSuZ5lx/HQ0pRgT9JFoxN0="
    - TWINE_USERNAME: theochem

cache:
  # More time is needed for caching due to the sheer size of the conda env.
  timeout: 1000
  directories:
    - ${HOME}/cache

install:
  # Disable deployment when TRAVIS_TAG is not set. This avoids duplicate deployments.
  - if [[ -z $TRAVIS_TAG ]]; then
      export ROBERTO_DEPLOY_BINARY=0 ROBERTO_DEPLOY_NOARCH=0;
    fi
  # Get a basic python 3 with pip to run roberto
  - python3 --version
  - wget --no-clobber -O ${HOME}/cache/get-pip.py https://bootstrap.pypa.io/get-pip.py || true
  - python3 ${HOME}/cache/get-pip.py --user
  - python3 -m pip install 'roberto<2.0.0' --user
  # Use development version of Roberto to avoid having to make too many releases.
  # - python3 -m pip install git+https://github.com/theochem/roberto#egg=roberto --user

script:
  # Instead of simply calling `rob`, we do something that always works on osx too.
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      python3 -m roberto robot;
    else
      python3 -m roberto;
    fi

before_cache:
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/conda-bld
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/locks
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/pkgs
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/var
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/conda-bld
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/locks
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/pkgs
  - rm -rf ${ROBERTO_CONDA_BASE_PATH}/envs/*/var
