linters:
  - cppcheck:
  - cpplint:
  - doxygen:
  - flake8:
  - header:
      header: ../../HEADER
  - import:
      packages: ['math']
  - namespace:
      forbidden: ['math']
  - pylint:
  - pycodestyle:
  - autopep8:
  - black:
  - yapf:
  - pydocstyle:
  - whitespace:
  - yamllint:
  - rst-lint:
