linters:
  - cppcheck:
  - cpplint:
      script: ../../cpplint.py
  - doxygen:
  - flake8:
  - header:
      header: ../../HEADER
  - import:
      packages: ['math']
  - namespace:
      forbidden: ['math']
  - pylint:
  - pycodestyle:
  - pydocstyle:
  - whitespace:
  - yamllint:
