package:
  name: cppcheck
  version: '1.80'
source:
  fn: 1.80.tar.gz
  sha256: 20863db018d69c33648bdedcdc9d81d818b9064cc4333f0d4dc45e114bd0f000
  url: https://github.com/danmar/cppcheck/archive/1.80.tar.gz

build:
  number: 4
  string: 4

requirements:
  build:
    - cmake
    - gcc      # [linux]
  run:
    - libgcc   # [linux]

about:
  description:
    Cppcheck is a static analysis tool for C/C++ code. Unlike C/C++ compilers
    and many other analysis tools it does not detect syntax errors in the code.
    Cppcheck primarily detects the types of bugs that the compilers normally do
    not detect. The goal is to detect only real errors in the code (i.e. have
    zero false positives).
  home: 'https://github.com/danmar/cppcheck'
  license: 'GPLv3'
  summary: 'A static analysis tool for C/C++ code.'
