# This is based on the doxygen recipe from conda-forge with some small alterations.
package:
  name: doxygen
  version: 1.8.13

source:
  url: ftp://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.13.src.tar.gz
  fn: doxygen-1.8.13.src.tar.gz
  sha256: af667887bd7a87dc0dbf9ac8d86c96b552dfb8ca9c790ed1cbffaa6131573f6b
  patches:
  - find_iconv.patch

build:
  number: 2
  string: 2

requirements:
  build:
  - cmake
  - libiconv
  - bison
  - flex
  - gcc      # [linux]
  run:
  - m4
  - libiconv
  - libgcc   # [linux]

test:
  commands:
    - doxygen -v

about:
    home: http://www.stack.nl/~dimitri/doxygen/index.html
    license: GPLv3
    summary: 'Documentation generator for C++ and other languages.'
